#:schema node_modules/wrangler/config-schema.json
name = "user-prisma-api"
main = "src/index.ts"
compatibility_date = "2024-05-12"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "user-prisma-api"
database_id = "ac872d93-c78e-474b-8a47-e876e640ae40"
migrations_dir = "prisma/migrations"